//! Streaming token generation for the llama.cpp adapter: the `spawn_blocking`
//! worker (`run_streaming_generation`) and its UTF-8-safe decode loop
//! (`decode_step` / `stream_tokens`). Split out of `super` for readability;
//! shares the adapter's private `Inner` state.

use std::sync::{Arc, Mutex};

use kernel::types::error::GatewayError;
use kernel::types::request::StreamChunk;
use llama_cpp_2::{
    context::LlamaContext, llama_batch::LlamaBatch, model::LlamaModel, sampling::LlamaSampler,
    token::LlamaToken,
};

use super::*;

/// Bundled inputs to [`run_streaming_generation`] — grouped into one value so
/// the `spawn_blocking` worker call site doesn't carry five independent
/// fields alongside `inner` and `tx`.
pub(super) struct StreamingGenerationRequest {
    pub(super) adapter_id: String,
    pub(super) prompt_tokens: Vec<LlamaToken>,
    pub(super) max_new: u32,
    pub(super) temperature: f32,
    pub(super) seed: u32,
}

/// Streaming generation body — runs in a `spawn_blocking` worker.
/// Sends a [`StreamChunk`] for every UTF-8-valid prefix increment of
/// the accumulated bytes, plus a final empty-content chunk with
/// `finish_reason` set to `"stop"` (EOS) or `"length"` (hit max_new).
///
/// Why UTF-8-prefix-based chunking and not "one chunk per token":
/// tokenizers can split multi-byte codepoints across tokens (common in
/// CJK / emoji / non-Latin scripts). Naively decoding each token in
/// isolation produces invalid UTF-8 fragments and either errors out or
/// emits U+FFFD replacement characters. Accumulating bytes and only
/// emitting the longest valid UTF-8 prefix per step preserves the
/// original text exactly.
pub(super) fn run_streaming_generation(
    inner: Arc<Inner>,
    request: StreamingGenerationRequest,
    tx: tokio::sync::mpsc::Sender<Result<StreamChunk, GatewayError>>,
) {
    // `stream_tokens` runs setup → loop → flush and returns the finish reason
    // on a clean run. On any early exit it has already sent the error (or
    // stopped silently on receiver-dropped cancellation) and returns
    // `Err(())`, so the terminal chunk below is skipped — matching each of the
    // original seven `return`s exactly.
    if let Ok(finish_reason) = stream_tokens(&inner, &request, &tx) {
        let _ = tx.blocking_send(Ok(StreamChunk {
            content: String::new(),
            finish_reason: Some(finish_reason.into()),
            usage: None,
            tool_calls: Vec::new(),
        }));
    }
}

/// Build a `ProviderError` for the streaming adapter.
fn stream_error(adapter_id: &str, message: String) -> GatewayError {
    GatewayError::ProviderError {
        adapter: adapter_id.into(),
        message,
        status: None,
    }
}

/// Send an `Err` chunk and yield the `()` sentinel that the `?` operator
/// propagates. Every fallible step early-exits through this single path
/// (`.map_err(|e| emit_err(tx, stream_error(..)))?`), which is what collapses
/// the original seven hand-written `return`s into one. The send result is
/// ignored: the receiver may already be gone.
fn emit_err(tx: &tokio::sync::mpsc::Sender<Result<StreamChunk, GatewayError>>, e: GatewayError) {
    let _ = tx.blocking_send(Err(e));
}

/// Length of the longest valid UTF-8 prefix of `bytes`. Lets the streaming
/// loop ship only complete codepoints when a multi-byte character straddles
/// two tokens (common in CJK / emoji / non-Latin scripts).
fn valid_utf8_end(bytes: &[u8]) -> usize {
    match std::str::from_utf8(bytes) {
        Ok(_) => bytes.len(),
        Err(e) => e.valid_up_to(),
    }
}

/// Outcome of decoding one token in the streaming loop. `Emitted` means a
/// token was produced (and any now-complete UTF-8 text shipped) and the loop
/// should keep decoding; `EndOfGeneration` means an EOG token was sampled, so
/// the loop stops with `finish_reason = "stop"`.
enum StreamStep {
    Emitted,
    EndOfGeneration,
}

/// Mutable per-generation decode state threaded through each [`decode_step`].
/// Bundled into one value so the step helper stays within a sane argument
/// count and the loop and the trailing flush share one owner for the UTF-8
/// buffer. `ctx` borrows the locked context guard for the run's duration.
struct StreamDecode<'ctx> {
    ctx: &'ctx mut LlamaContext<'static>,
    sampler: LlamaSampler,
    batch: LlamaBatch<'static>,
    /// Raw generated bytes; may end mid-codepoint between steps.
    buf: Vec<u8>,
    /// How many bytes of `buf` have already been shipped as chunks.
    emitted: usize,
}

/// Decode one token: sample, ship any now-complete UTF-8 text, then feed the
/// token back in for the next step. Returns `EndOfGeneration` on an EOG token
/// so the loop can stop with `finish_reason = "stop"`. Bubbles `Err(())` after
/// `emit_err` has already sent the error — or silently, on receiver-dropped
/// cancellation — so the caller stops without emitting a terminal chunk.
fn decode_step(
    state: &mut StreamDecode<'_>,
    model: &LlamaModel,
    tx: &tokio::sync::mpsc::Sender<Result<StreamChunk, GatewayError>>,
    adapter_id: &str,
    next_pos: i32,
) -> Result<StreamStep, ()> {
    let token = state.sampler.sample(state.ctx, state.batch.n_tokens() - 1);
    state.sampler.accept(token);

    if model.is_eog_token(token) {
        return Ok(StreamStep::EndOfGeneration);
    }

    let bytes = model
        .token_to_piece_bytes(token, 32, false, None)
        .map_err(|e| {
            emit_err(
                tx,
                stream_error(adapter_id, format!("token_to_piece_bytes: {e}")),
            )
        })?;
    state.buf.extend_from_slice(&bytes);

    // Ship the longest newly-valid UTF-8 prefix beyond `emitted`.
    let valid_end = valid_utf8_end(&state.buf);
    if valid_end > state.emitted {
        // Safety: [0..valid_end] was just confirmed to be valid UTF-8.
        let new_text = std::str::from_utf8(&state.buf[state.emitted..valid_end])
            .expect("valid prefix")
            .to_string();
        state.emitted = valid_end;
        if tx
            .blocking_send(Ok(StreamChunk {
                content: new_text,
                finish_reason: None,
                usage: None,
                tool_calls: Vec::new(),
            }))
            .is_err()
        {
            // Receiver dropped — caller cancelled the stream. Stop early.
            return Err(());
        }
    }

    state.batch.clear();
    state.batch.add(token, next_pos, &[0], true).map_err(|e| {
        emit_err(
            tx,
            stream_error(adapter_id, format!("batch.add (step): {e}")),
        )
    })?;
    state
        .ctx
        .decode(&mut state.batch)
        .map_err(|e| emit_err(tx, stream_error(adapter_id, format!("decode (step): {e}"))))?;
    Ok(StreamStep::Emitted)
}

/// Setup → loop { [`decode_step`] } → flush. Returns the finish reason
/// (`"stop"` on EOG, `"length"` on hitting `max_new`) on a clean run; every
/// early exit returns `Err(())` after `emit_err` has sent the error (or
/// silently on cancellation), so the caller skips the terminal chunk.
fn stream_tokens(
    inner: &Inner,
    request: &StreamingGenerationRequest,
    tx: &tokio::sync::mpsc::Sender<Result<StreamChunk, GatewayError>>,
) -> Result<&'static str, ()> {
    let adapter_id = request.adapter_id.as_str();
    let prompt_tokens = &request.prompt_tokens;

    // Lock the context for the duration of this generation. Other concurrent
    // calls on the same adapter queue behind this lock; this matches the
    // non-streaming generate() path.
    let mut guard = inner.context.lock().map_err(|_| {
        emit_err(
            tx,
            stream_error(adapter_id, "context mutex poisoned".into()),
        )
    })?;
    let ctx = &mut guard.0;
    ctx.clear_kv_cache();

    // Feed the prompt: mark only the last token for logits.
    let mut batch = LlamaBatch::new(prompt_tokens.len().max(1), 1);
    let last_prompt = prompt_tokens.len().saturating_sub(1);
    for (pos, &token) in prompt_tokens.iter().enumerate() {
        batch
            .add(token, pos as i32, &[0], pos == last_prompt)
            .map_err(|e| {
                emit_err(
                    tx,
                    stream_error(adapter_id, format!("batch.add (prompt): {e}")),
                )
            })?;
    }
    ctx.decode(&mut batch).map_err(|e| {
        emit_err(
            tx,
            stream_error(adapter_id, format!("decode (prompt): {e}")),
        )
    })?;

    let sampler = if request.temperature <= 0.0 {
        LlamaSampler::greedy()
    } else {
        LlamaSampler::chain_simple([
            LlamaSampler::temp(request.temperature),
            LlamaSampler::dist(request.seed),
        ])
    };

    // UTF-8-safe streaming buffer. `emitted` tracks how many bytes have
    // already been shipped as chunks; we only ship bytes that form a valid
    // UTF-8 prefix.
    let start_pos = prompt_tokens.len() as i32;
    let mut state = StreamDecode {
        ctx,
        sampler,
        batch,
        buf: Vec::new(),
        emitted: 0,
    };
    let mut finish_reason = "length";

    for offset in 0..request.max_new {
        let next_pos = start_pos + offset as i32;
        match decode_step(&mut state, &inner.model, tx, adapter_id, next_pos)? {
            StreamStep::Emitted => {}
            StreamStep::EndOfGeneration => {
                finish_reason = "stop";
                break;
            }
        }
    }

    // Flush any trailing valid bytes the loop didn't emit (rare — would only
    // happen if the final iteration appended bytes that sat past `emitted` but
    // were a valid prefix).
    let valid_end = valid_utf8_end(&state.buf);
    if valid_end > state.emitted
        && let Ok(text) = std::str::from_utf8(&state.buf[state.emitted..valid_end])
    {
        let _ = tx.blocking_send(Ok(StreamChunk {
            content: text.to_string(),
            finish_reason: None,
            usage: None,
            tool_calls: Vec::new(),
        }));
    }

    Ok(finish_reason)
}
